# Generated by Django 4.0.4 on 2022-12-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_normal_skill',
            field=models.BooleanField(default=False),
        ),
    ]
