# Generated by Django 4.0.4 on 2022-12-07 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill_is_normal_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='is_normal_skill',
            new_name='is_coding_skill',
        ),
    ]
